name: Python CI

on:
  push:
    branches:
      - main  # Запуск на зміни в гілці main
  pull_request:
    branches:
      - main  # Запуск при створенні pull request до main

jobs:
  test:
    runs-on: ubuntu-latest  # Запуск на останній версії Ubuntu

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Вибір версії Python (змініть на потрібну)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Встановлення залежностей із requirements.txt

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE  # Перехід до кореневої директорії
          pytest --maxfail=1 --disable-warnings -q

      - name: Install PEP8 checker
        run: pip install pycodestyle

      - name: Run PEP8 check
        run: |
          pycodestyle --max-line-length=79 .  # Запуск перевірки коду на відповідність PEP8
